### ISSUE TITLE
Set HP more than 100

### ISSUE THREAD

**Issue by imp87** [resourcemod/resourcemod#4]
Is it possible to increase the maximum health points (HP) beyond the standard limit of 100, potentially up to a maximum of 200?

![image](https://github.com/resourcemod/resourcemod/assets/95252622/028d6476-9f51-426b-810c-d81ac4e0d4cd)

**Comment by twelvee** [comment]
![image](https://github.com/resourcemod/resourcemod/assets/3142318/d64dbb2c-a845-458e-bd48-81f823680105)
`event.GetPlayer().hp = 999;` works fine for me

**Comment by imp87** [comment]
On "player_spawn" its not working. If i using a timer, the server crashes.

**Comment by twelvee** [comment]
> On "player_spawn" its not working. If i using a timer, the server crashes.

player_spawn is broken rn, will fix it in #3

**Comment by imp87** [comment]
Thanks! i will close this issue.
